#!/bin/bash

if [ $# -le 0 ]; then 
	echo "Provide youtube playlist link or use --help for help"
else
	if [ "$1" == "--help" ] ; then
		echo "Usage: youtube-dl-playlist youtube_playlist [optional parameters]"
		echo "Parameters: "
		echo -e "-d [directory to save to]"
		echo -e "-a [Increment. 1 = 1,2,3 ;01 = 01,02,03...] -> [auto number videos]"
		echo -e "\nThis script uses youtube-dl which is property of https://ytdl-org.github.io/youtube-dl/about.html \n"
		echo "For all complete info on how to use youtube-dl visit https://github.com/ytdl-org/youtube-dl"
		echo "Again, I take no credit whatsover for the development of youtube-dl, I just got some request on a script to auto download a playlist"
		exit 0
	fi
	if ! which youtube-dl ; then
		echo "youtube-dl missing... downloading..."
		sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
		sudo chmod a+rx /usr/local/bin/youtube-dl
		echo "download complete, downloading your playlist now."
	fi
	autonumber=""
	directory=""
	while getopts ":d:a:" opt; do
		case ${opt} in
			d)
				directory=$OPTARG
				;;
			a)
				autonumber=`echo "%(playlist_index)$OPTARG"d-`
				;;
			\?)
				echo "Invalid option: $OPTARG" 1>&2
				;;
		esac
	done
	shift $((OPTIND-1))
	[ "${1:-}" = "--" ] && shift
	playlist=$@
	output="$autonumber%(title)s.%(ext)s"
	if [ -d $diretory ] ;then 
		output="$directory/$autonumber%(title)s.%(ext)s"
	fi
	echo $output
	youtube-dl -f best -ciw -o $output $playlist
fi
