#!/bin/bash

if [ $# -le 0 ]; then 
	echo "Provide youtube playlist link or use --help for help"
else
	if [ "$1" == "--help" ] ; then
		echo "Usage: youtube-dl-playlist youtube_playlist [optional parameters]"
		echo "Parameters: "
		echo -e "-d [directory to save to]"
		echo -e "-a [auto number videos]"
		echo -e "\nThis script uses youtube-dl which is property of https://ytdl-org.github.io/youtube-dl/about.html \n"
		echo "For all complete info on how to use youtube-dl visit https://github.com/ytdl-org/youtube-dl"
		echo "Again, I take no credit whatsover for the development of youtube-dl, I just got some request on a script to auto download a playlist"
		exit 0
	fi
	if ! which youtube-dl ; then
		echo "youtube-dl missing... downloading..."
		sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
		sudo chmod a+rx /usr/local/bin/youtube-dl
		echo "download complete, downloading your playlist now."
	fi
	autonumber=""
	directory=""
	while getopts ":t:f:" opt; do
		case ${opt} in
			d)
				directory=$OPTARG
				;;
			a)
				autonumber="%(video_index)1d-"
				echo $s
				;;
			\?)
				echo "Invalid option: $OPTARG" 1>&2
				;;
		esac
	done
	shift $((OPTIND-1))
	[ "${1:-}" = "--" ] && shift
	playlist=$@
	if [ "directory" != "" ] ;then
		pushd $directory 
		youtube-dl -f best -ciw -o "$autonumber%(title)s.%(ext)s" $playlist
		popd
	else
		youtube-dl -f best -ciw -o "$autonumber%(title)s.%(ext)s" $playlist
	fi
fi
